### ISSUE TITLE
Standardized folders for logos and badges

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/figanos#115]
### Addressing a Problem?

When making a plot, the default approach is to use the Ouranos logo when `figanos.matplotlib.utils.plot_logo()` is called.

This behaviour is a bit odd, considering that this project is licensed under the Apache v2.0 License, specifically because we don't want to give a license for people to use our logos or create products that have our endorsements. In the event that someone not from Ouranos wants to use `figanos` and forgets to manually set the call signature, they'll have infringed on our software license.

### Potential Solution

Using the `platformdirs` library, we can generate a `config` folder in the user's `$HOME` directory that, when `figanos.matplotlib.utils.plot_logo()` is called, grabs a file that adheres to the regex `.+logo.png`. This becomes the new default logo image whenever called.

This library would remove the Ouranos logo from the source code, and we would simply need to add the `ouranos-logo.png` to our config folders.

The `platformdirs` library is already installed by default for users of and projects based on `xclim` as of v0.45.0.

### Additional context

https://github.com/platformdirs/platformdirs

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by juliettelavoie** [comment]
I don't like to force people to have the logo on their computer... This is a library specifically made to create Ouranos (not just general climate) figures, it feels weird to not provide the logo.. maybe we change the license ?

**Comment by Zeitsperre** [comment]
The license is perfect (or as best as we can ask) for our use case and for adhering to a free and open source approach; My gripe is mainly that we package the logos as part of the data in the installed package.

How would you feel about keeping the Ouranos logos in the repository, but they aren't installed by default. Then we could simply make a tiny helper function (`install_ouranos_logos()`) that collects those logos and places them in the proper folder? That way, the Ouranos logos are only shared if a user explicitly demands them.

**Comment by cothel** [comment]
"That way, the Ouranos logos are only shared if a user explicitly demands them."
I would prefer "the Ouranos logos are only shared if a user is allowed to use them." 
Like staff...

**Comment by juliettelavoie** [comment]
https://opensource.stackexchange.com/questions/500/does-being-open-sourced-mean-others-can-use-my-logo

Est-ce que le logo Ouranos est trademark ? Voir réponse de Shane Curcuru.

**Comment by juliettelavoie** [comment]
Je veux juste que ça reste le plus simple possible pour les usagers haha

**Comment by Zeitsperre** [comment]
@cothel 

As of right now, only Ouranos employees are _allowed_ to use them. The Apache v2.0 Licence is very clear that using the library doesn't entitle users to put our logos on their derived products (or modify our logo, or pretend to be Ouranos, etc.). My gripe (and it really is a gripe) is that we make it very easy for anyone to accidentally commit a licensing violation.

My proposal here is to add a function that is effectively the equivalent of an "Are you allowed to use the Ouranos logo?" check. They run the function once, it downloads the image into their `XDG_HOME_CONFIG` and that's all.

(exaggeration for fun) Having the logo behind a VPN and firewall, on a protected network drive, requiring multifactor authentication, two people manually turning keys in unison, and an active employee ID, etc., is not what I have in mind.

**Comment by sarahclaude** [comment]
If its simple as "Are you allowed to use the Ouranos logo" I think it would be alright for future users.
