### ISSUE TITLE
Can't import figanos

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/figanos#117]
### Generic Issue

* figanos version: 0.2
* Python version: 3.9
* Operating System: linux

### Description

I want to install the latest figanos  (to use hatchmap).

### What I Did

In my env and in the figanos directory
```
pip install . 
```
and then 
```import figanos.matplotlib as sp```

### What I Received

FileNotFoundError: [Errno 2] No such file or directory: '/exec/jlavoie/.conda/espo-fig/lib/python3.9/site-packages/figanos/data/terms.yml'

That file is present in my figanos directory, but it seems like it is not seen in the pip install ...

@aulemahal  Do I have to do something special ? I assume there is no `make translate` here as I don't see it in the makefile ?

**Comment by juliettelavoie** [comment]
it works with `pip install -e .`

**Comment by Zeitsperre** [comment]
Looks like there's a file missing from the `Manifest.in`. I can take a look tomorrow.
