### ISSUE TITLE
Colormap page

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/figanos#126]
### Generic Issue

I want to add a page in the docs that looks like: https://matplotlib.org/stable/users/explain/colors/colormaps.html

It is possible to pass `cmap=temp_seq` to our functions if your dataset doesn't have the right variable name, but you have to know the ipcc names. 

It would be nice to have them available without having to dig in the repo or the ipcc style guide.

**Comment by cothel** [comment]
Même si les noms de variables sont différent, il serait aussi possible d'utiliser des mots-clés provenant des standard_name ou bien des long_name du fichier afin de les lier par défaut aux divers styles ipcc. On aurait alors des familles de variables associées à un style qui aurait de très bonnes chance de faire l'affaire. D'autres mots-clés pourraient aussi déterminer si on opte pour une palette cyclique (ex "direction"), discrète (ex "class" ) ou non. 
Tout ce vocabulaire est de toute façon codifié dans les règles de syntaxe CF pour les standard_names, suivi par le GIEC.
Ça prend un peu code mais qui serait basé sur des règles quand même assez fiables.

**Comment by juliettelavoie** [comment]
c'est déjà comme ça pour les variable! https://github.com/Ouranosinc/figanos/blob/main/figanos/data/ipcc_colors/variable_groups.json

discrete est déjà un argument, alors il ne peut pas être un mot-clé. Il n'y a pas de palette de l'ipcc cyclique.

Mais les gens veulent quand même pouvoir voir les options et les noms de cmap facilement.

**Comment by juliettelavoie** [comment]
Je me demande si c'est mieux d'ajouter ça à Getting Started ou faire sa propre page "couleur". Dans le 2e cas, je bougerais peut-être aussi certaines cellules de getting started avec les patch de couleurs pour les timeseries.
@sarahclaude qu'est-ce que tu en penses ?

**Comment by sarahclaude** [comment]
Je penses que c'est une bonne idée d'avoir une page distincte comme le plus gros avantage de figanos est d'avoir des cmap uniforme à travers nos figures. Si j'ai bien compris tu aussi ajouter une fonction qui retourne un genre de dictionnaire associant les variables avec les cmaps?

**Comment by juliettelavoie** [comment]
ben ce yml existe deja, mais on pourrait le rendre visible à travers une fonction.

**Comment by sarahclaude** [comment]
De quel yml tu parles? Je penses qu'il faudrait combiner terms.yml avec les fichiers textes dans categoricals/ contiunuous_rgb_0-255. Je peux m'occuper d'ajouter cette fonction si tu préfères te concentrer sur l'ajout de docs.
