### ISSUE TITLE
Transparent option

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/figanos#183]
### Addressing a Problem?

The matplotlib stylesheet are very nice feature of figanos, but I think they can be even cooler.

### Potential Solution

Transparent background is a simple addition to the figures that makes them go from :smile:  to :sunglasses: when used in poster/presentations with non-white background.

```python3
plt.rcParams.update({
    "figure.facecolor":  (1.0, 1.0, 1.0, 0.0),
    "axes.facecolor":    (1.0, 1.0, 1.0, 0.3),
    "savefig.facecolor": (1.0, 1.0, 1.0, 0.0),
})
```

These lines could be added to a fourth stylesheet `transparent` ?

### Additional context

![Before](https://github.com/Ouranosinc/figanos/assets/20629530/fa18d2d6-c885-4438-9d4c-f191517be2f6)
![After](https://github.com/Ouranosinc/figanos/assets/20629530/4f6931d1-c2e0-423d-aa52-a6d4b597da43)

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

**Comment by juliettelavoie** [comment]
j'aime l'idée !
