### ISSUE TITLE
Add the ability to easily create custom colormaps

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/figanos#79]
### Description

In some cases, it might be useful to have the ability to easily create a fully custom colormap, with a color progression of your choosing, such as what was done in #13. I think the idea would be to 

- have a list of colors that are recognized
- have the ability to provide the RGB

Then from what is provided, we construct the colormap.

Here's the (really rough and hard-coded) code in #13.
```
def _atlas_cmap(plot_type):
    """ Creates the color scheme."""
      red = [i / 255 for i in (255, 28, 12)]
      orange = [i / 255 for i in (255, 178, 15)]
      white = [i / 255 for i in (255, 255, 255)]
      l_blue = [i / 255 for i in (19, 191, 255)]
      blue = [i / 255 for i in (11, 34, 224)]
      cmap = [red, orange, white, l_blue, blue]

    return matplotlib.colors.LinearSegmentedColormap.from_list("custom_cmap", colors=cmap, N=256)
```

**Comment by sarahclaude** [comment]
Add exemple to figanos and detail cmap usage in docs: https://matplotlib.org/stable/tutorials/colors/colormap-manipulation.html#directly-creating-a-segmented-colormap-from-a-list
